// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Blog = Collections['blogs']['schema']['_output']
export declare const blogs: Blog[]

export type Extension = Collections['extensions']['schema']['_output']
export declare const extensions: Extension[]

export type Hardware = Collections['hardware']['schema']['_output']
export declare const hardware: Hardware[]

export type Software = Collections['software']['schema']['_output']
export declare const software: Software[]

export type Project = Collections['projects']['schema']['_output']
export declare const projects: Project[]
